### PR TITLE
GAE Flexible Environment regions

### LINKED ISSUE #57: Unknown App Engine Region Code: europe-west2-a
I used Google App Engine Flexible Environment and I get error:
```
PHP Notice: Exception: Unknown App Engine Region Code: europe-west2-a in 
/app/vendor/a1comms/gae-support-laravel/src/A1comms/GaeSupportLaravel/Integration/TaskQueue/Client.php:61
```

### PR DESCRIPTION
**Pull request by matthewnessworthy**
Closes #57

### CODE REVIEW

**Review by iamacarpet — APPROVED** [review]
Nice one, thanks a bunch @matthewnessworthy , you are a legend!

**Comment by iamacarpet** [comment]
@matthewnessworthy , do you want me to cherry-pick this into the L6.0 branch too?

**Comment by matthewnessworthy** [comment]
@iamacarpet yes please

**Comment by iamacarpet** [comment]
@matthewnessworthy , thanks, done, plus pulled in some other missing commits.

**Pull request merged**
